In [5]:
import pandas as pd

df= pd.read_csv("DataCoSupplyChainDataset.csv", encoding = "latin1")

In [6]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [8]:
df.shape

(180519, 53)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

In [10]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [11]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='str')

In [12]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_").str.replace("-","_")

In [16]:
df.columns.tolist()

['type',
 'days_for_shipping_(real)',
 'days_for_shipment_(scheduled)',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_email',
 'customer_fname',
 'customer_id',
 'customer_lname',
 'customer_password',
 'customer_segment',
 'customer_state',
 'customer_street',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date_(dateorders)',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'order_zipcode',
 'product_card_id',
 'product_category_id',
 'product_description',
 'product_image',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date_(dateorders)',
 'shipping_mode']

In [17]:
missing = df.isnull().sum()

missing[missing >0].sort_values(ascending=False)

product_description    180519
order_zipcode          155679
customer_lname              8
customer_zipcode            3
dtype: int64

In [20]:
missing_report = pd.DataFrame({'missing_count': df.isnull().sum(),'missing_percentage' : (df.isnull().sum() / len(df) *100).round(2)})
missing_report[missing_report['missing_count']>0]

                     missing_count  missing_percentage
customer_lname                   8                0.00
customer_zipcode                 3                0.00
order_zipcode               155679               86.24
product_description         180519              100.00

In [21]:
df= df.drop(columns =['product_description'])

In [22]:
df=df.drop(columns =['order_zipcode'])

In [23]:
df['customer_lname'] = df['customer_lname'].fillna('unknown')

In [26]:
df['customer_zipcode'] = df['customer_zipcode'].fillna(
    df['customer_zipcode'].median()
)

In [31]:
df.isnull().sum()

type                             0
days_for_shipping_(real)         0
days_for_shipment_(scheduled)    0
benefit_per_order                0
sales_per_customer               0
delivery_status                  0
late_delivery_risk               0
category_id                      0
category_name                    0
customer_city                    0
customer_country                 0
customer_email                   0
customer_fname                   0
customer_id                      0
customer_lname                   0
customer_password                0
customer_segment                 0
customer_state                   0
customer_street                  0
customer_zipcode                 0
department_id                    0
department_name                  0
latitude                         0
longitude                        0
market                           0
order_city                       0
order_country                    0
order_customer_id                0
order_date_(dateorders)          0
order_id                         0
order_item_cardprod_id           0
order_item_discount              0
order_item_discount_rate         0
order_item_id                    0
order_item_product_price         0
order_item_profit_ratio          0
order_item_quantity              0
sales                            0
order_item_total                 0
order_profit_per_order           0
order_region                     0
order_state                      0
order_status                     0
product_card_id                  0
product_category_id              0
product_image                    0
product_name                     0
product_price                    0
product_status                   0
shipping_date_(dateorders)       0
shipping_mode                    0
dtype: int64

In [30]:
df.dtypes

type                                 str
days_for_shipping_(real)           int64
days_for_shipment_(scheduled)      int64
benefit_per_order                float64
sales_per_customer               float64
delivery_status                      str
late_delivery_risk                 int64
category_id                        int64
category_name                        str
customer_city                        str
customer_country                     str
customer_email                       str
customer_fname                       str
customer_id                        int64
customer_lname                       str
customer_password                    str
customer_segment                     str
customer_state                       str
customer_street                      str
customer_zipcode                 float64
department_id                      int64
department_name                      str
latitude                         float64
longitude                        float64
market                               str
order_city                           str
order_country                        str
order_customer_id                  int64
order_date_(dateorders)              str
order_id                           int64
order_item_cardprod_id             int64
order_item_discount              float64
order_item_discount_rate         float64
order_item_id                      int64
order_item_product_price         float64
order_item_profit_ratio          float64
order_item_quantity                int64
sales                            float64
order_item_total                 float64
order_profit_per_order           float64
order_region                         str
order_state                          str
order_status                         str
product_card_id                    int64
product_category_id                int64
product_image                        str
product_name                         str
product_price                    float64
product_status                     int64
shipping_date_(dateorders)           str
shipping_mode                        str
dtype: object

In [33]:
df['order_date_(dateorders)'] = pd.to_datetime(df['order_date_(dateorders)'])

In [34]:
df['shipping_date_(dateorders)'] = pd.to_datetime(df['shipping_date_(dateorders)'])

In [35]:
df[['order_date_(dateorders)' ,'shipping_date_(dateorders)']].dtypes

order_date_(dateorders)       datetime64[us]
shipping_date_(dateorders)    datetime64[us]
dtype: object

In [41]:
df['order_year'] = df['order_date_(dateorders)'].dt.year
df['order_month'] = df['order_date_(dateorders)'].dt.month
df['order_month_name'] = df['order_date_(dateorders)'].dt.month_name()
df['shipping_days'] = (df['shipping_date_(dateorders)'] - df['order_date_(dateorders)']).dt.days

In [42]:
df[['order_year','order_month','order_month_name','shipping_days']].head()

   order_year  order_month order_month_name  shipping_days
0        2018            1          January              3
1        2018            1          January              5
2        2018            1          January              4
3        2018            1          January              3
4        2018            1          January              2

In [44]:
numeric_cols = df.select_dtypes(include='number').columns.tolist()
numeric_cols

['days_for_shipping_(real)',
 'days_for_shipment_(scheduled)',
 'benefit_per_order',
 'sales_per_customer',
 'late_delivery_risk',
 'category_id',
 'customer_id',
 'customer_zipcode',
 'department_id',
 'latitude',
 'longitude',
 'order_customer_id',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'product_card_id',
 'product_category_id',
 'product_price',
 'product_status',
 'order_year',
 'order_month',
 'shipping_days']

In [46]:
df[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
days_for_shipping_(real),180519.0,3.497654,1.623722,0.000000,2.000000,3.000000,5.000000,6.000000
days_for_shipment_(scheduled),180519.0,2.931847,1.374449,0.000000,2.000000,4.000000,4.000000,4.000000
benefit_per_order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
sales_per_customer,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
late_delivery_risk,180519.0,0.548291,0.497664,0.000000,0.000000,1.000000,1.000000,1.000000
category_id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
customer_id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
customer_zipcode,180519.0,35920.852021,37542.209723,603.000000,725.000000,19380.000000,78207.000000,99205.000000
department_id,180519.0,5.443460,1.629246,2.000000,4.000000,5.000000,7.000000,12.000000
latitude,180519.0,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
longitude,180519.0,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
order_customer_id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
order_id,180519.0,36221.894903,21045.379569,1.000000,18057.000000,36140.000000,54144.000000,77204.000000
order_item_cardprod_id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
order_item_discount,180519.0,20.664741,21.800901,0.000000,5.400000,14.000000,29.990000,500.000000
order_item_discount_rate,180519.0,0.101668,0.070415,0.000000,0.040000,0.100000,0.160000,0.250000
order_item_id,180519.0,90260.000000,52111.490959,1.000000,45130.500000,90260.000000,135389.500000,180519.000000
order_item_product_price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
order_item_profit_ratio,180519.0,0.120647,0.466796,-2.750000,0.080000,0.270000,0.360000,0.500000
order_item_quantity,180519.0,2.127638,1.453451,1.000000,1.000000,1.000000,3.000000,5.000000
sales,180519.0,203.772096,132.273077,9.990000,119.980003,199.919998,299.950012,1999.989990
order_item_total,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
order_profit_per_order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
product_card_id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
product_category_id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
product_price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
product_status,180519.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
order_year,180519.0,2015.971150,0.829429,2015.000000,2015.000000,2016.000000,2017.000000,2018.000000
order_month,180519.0,6.235449,3.403571,1.000000,3.000000,6.000000,9.000000,12.000000
shipping_days,180519.0,3.471856,1.670471,0.000000,2.000000,3.000000,5.000000,6.000000

In [47]:
(df[numeric_cols] < 0).sum().sort_values(ascending=False)

longitude                        180414
benefit_per_order                 33784
order_profit_per_order            33784
order_item_profit_ratio           33784
latitude                              9
sales_per_customer                    0
category_id                           0
late_delivery_risk                    0
customer_zipcode                      0
customer_id                           0
department_id                         0
order_customer_id                     0
days_for_shipment_(scheduled)         0
days_for_shipping_(real)              0
order_item_cardprod_id                0
order_id                              0
order_item_id                         0
order_item_discount                   0
order_item_product_price              0
order_item_quantity                   0
sales                                 0
order_item_discount_rate              0
order_item_total                      0
product_card_id                       0
product_category_id                   0
product_price                         0
product_status                        0
order_year                            0
order_month                           0
shipping_days                         0
dtype: int64

In [48]:
df['shipping_days'].describe()

count    180519.000000
mean          3.471856
std           1.670471
min           0.000000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: shipping_days, dtype: float64

In [49]:
(df['shipping_days'] <0).sum()

np.int64(0)

In [51]:
df['shipping_days'].value_counts().sort_index()

shipping_days
0     9737
2    56618
3    28765
4    28513
5    28163
6    28723
Name: count, dtype: int64

In [59]:
outlier_cols = df.select_dtypes(include='number').columns
for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR= Q3-Q1

    lower = Q1 - 1.5 *IQR
    upper = Q3 - 1.5 *IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    print(col)
    print("lower:" ,lower)
    print("upper:", upper)
    print("outliers:",outliers)
    print("-" * 40)

days_for_shipping_(real)
lower: -2.5
upper: 0.5
outliers: 175439
----------------------------------------
days_for_shipment_(scheduled)
lower: -1.0
upper: 1.0
outliers: 142968
----------------------------------------
benefit_per_order
lower: -79.70000457500001
upper: -21.900001525000008
outliers: 169367
----------------------------------------
sales_per_customer
lower: -110.14999760000002
upper: 32.86999899999998
outliers: 176462
----------------------------------------
late_delivery_risk
lower: -1.5
upper: -0.5
outliers: 180519
----------------------------------------
category_id
lower: -22.5
upper: 4.5
outliers: 179682
----------------------------------------
customer_id
lower: -6522.25
upper: -1.75
outliers: 180519
----------------------------------------
customer_zipcode
lower: -115498.0
upper: -38016.0
outliers: 180519
----------------------------------------
department_id
lower: -0.5
upper: 2.5
outliers: 178040
----------------------------------------
latitude
lower: -13.255845065000003
upper: 7.758339884999998
outliers: 180519
----------------------------------------
longitude
lower: -146.559906005
upper: -114.48417663499998
outliers: 146382
----------------------------------------
order_customer_id
lower: -6522.25
upper: -1.75
outliers: 180519
----------------------------------------
order_id
lower: -36073.5
upper: 13.5
outliers: 180480
----------------------------------------
order_item_cardprod_id
lower: -498.5
upper: 102.5
outliers: 179339
----------------------------------------
order_item_discount
lower: -31.484999417500003
upper: -6.894999742500001
outliers: 180519
----------------------------------------
order_item_discount_rate
lower: -0.1399999965
upper: -0.019999999500000004
outliers: 180519
----------------------------------------
order_item_id
lower: -90258.0
upper: 1.0
outliers: 180518
----------------------------------------
order_item_product_price
lower: -174.98500825
upper: -24.995002749999998
outliers: 180519
----------------------------------------
order_item_profit_ratio
lower: -0.3400000259999999
upper: -0.06000000999999994
outliers: 168045
----------------------------------------
order_item_quantity
lower: -2.0
upper: 0.0
outliers: 180519
----------------------------------------
sales
lower: -149.97500980000007
upper: 29.99499899999995
outliers: 178142
----------------------------------------
order_item_total
lower: -110.14999760000002
upper: 32.86999899999998
outliers: 176462
----------------------------------------
order_profit_per_order
lower: -79.70000457500001
upper: -21.900001525000008
outliers: 169367
----------------------------------------
product_card_id
lower: -498.5
upper: 102.5
outliers: 179339
----------------------------------------
product_category_id
lower: -22.5
upper: 4.5
outliers: 179682
----------------------------------------
product_price
lower: -174.98500825
upper: -24.995002749999998
outliers: 180519
----------------------------------------
product_status
lower: 0.0
upper: 0.0
outliers: 0
----------------------------------------
order_year
lower: 2012.0
upper: 2014.0
outliers: 180519
----------------------------------------
order_month
lower: -6.0
upper: 0.0
outliers: 180519
----------------------------------------
shipping_days
lower: -2.5
upper: 0.5
outliers: 170782
----------------------------------------

In [60]:
df.select_dtypes(include='number').skew().sort_values(ascending=False)

product_price                    3.191020e+00
order_item_product_price         3.191020e+00
order_item_discount              3.039796e+00
order_item_total                 2.888446e+00
sales_per_customer               2.888446e+00
sales                            2.884249e+00
order_item_quantity              8.802518e-01
customer_zipcode                 4.909057e-01
customer_id                      4.887683e-01
order_customer_id                4.887683e-01
category_id                      3.616248e-01
product_category_id              3.616248e-01
order_item_discount_rate         3.409276e-01
department_id                    2.733206e-01
order_year                       1.774968e-01
product_card_id                  1.382546e-01
order_item_cardprod_id           1.382546e-01
days_for_shipping_(real)         8.477127e-02
order_month                      6.801874e-02
order_id                         3.270879e-02
product_status                   0.000000e+00
order_item_id                   -1.002129e-17
shipping_days                   -2.639385e-02
latitude                        -9.796267e-02
late_delivery_risk              -1.940742e-01
longitude                       -4.984611e-01
days_for_shipment_(scheduled)   -7.319983e-01
order_item_profit_ratio         -2.893531e+00
benefit_per_order               -4.741834e+00
order_profit_per_order          -4.741834e+00
dtype: float64

In [67]:
df['order_item_quantity'].value_counts().sort_index()

order_item_quantity
1    99134
2    20315
3    20350
4    20335
5    20385
Name: count, dtype: int64

In [68]:
df['order_item_quantity'].describe()

count    180519.000000
mean          2.127638
std           1.453451
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max           5.000000
Name: order_item_quantity, dtype: float64

In [69]:
df['sales'].describe()

count    180519.000000
mean        203.772096
std         132.273077
min           9.990000
25%         119.980003
50%         199.919998
75%         299.950012
max        1999.989990
Name: sales, dtype: float64

In [70]:
df.select_dtypes(include='object').columns

C:\Users\DIGNITY\AppData\Local\Temp\ipykernel_1256\3732952691.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['type', 'delivery_status', 'category_name', 'customer_city',
       'customer_country', 'customer_email', 'customer_fname',
       'customer_lname', 'customer_password', 'customer_segment',
       'customer_state', 'customer_street', 'department_name', 'market',
       'order_city', 'order_country', 'order_region', 'order_state',
       'order_status', 'product_image', 'product_name', 'shipping_mode',
       'order_month_name'],
      dtype='str')

In [71]:
df['order_status'].value_counts()

order_status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

In [72]:
df['delivery_status'].value_counts()

delivery_status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [73]:
df['customer_segment'].value_counts()

customer_segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

In [76]:
# sales acc to customer segment
df.groupby('customer_segment')['sales'].agg(['count','sum','mean']).sort_values('sum',ascending=False)

                  count           sum        mean
customer_segment
Consumer          93504  1.909579e+07  204.224313
Corporate         54789  1.116841e+07  203.843962
Home Office       32226  6.520538e+06  202.337802

In [77]:
df.groupby('delivery_status')['sales'].agg(['count','sum','mean']).sort_values('sum',ascending=False)

                   count           sum        mean
delivery_status
Late delivery      98977  2.012640e+07  203.344163
Advance shipping   41592  8.518008e+06  204.799190
Shipping on time   32196  6.570026e+06  204.063439
Shipping canceled   7754  1.570305e+06  202.515522

In [78]:
df.groupby('order_status')['sales'].agg(['count','sum','mean']).sort_values('sum',ascending=False)

                 count           sum        mean
order_status
COMPLETE         59491  1.209531e+07  203.313357
PENDING_PAYMENT  39832  8.106698e+06  203.522232
PROCESSING       21902  4.504064e+06  205.646231
PENDING          20227  4.120533e+06  203.714484
CLOSED           19616  4.022624e+06  205.068524
ON_HOLD           9804  1.981543e+06  202.115739
SUSPECTED_FRAUD   4062  8.259350e+05  203.332092
CANCELED          3692  7.443704e+05  201.617119
PAYMENT_REVIEW    1893  3.836537e+05  202.669655

In [79]:
df.groupby('market')['sales'].agg(['count','sum','mean']).sort_values('sum',ascending=False)

              count           sum        mean
market
Europe        50252  1.087240e+07  216.357494
LATAM         51594  1.027761e+07  199.201706
Pacific Asia  41260  8.273744e+06  200.526993
USCA          25799  5.066529e+06  196.384694
Africa        11614  2.294453e+06  197.559232

In [80]:
df.groupby('market')['order_profit_per_order'].agg(['count','sum','mean']).sort_values('sum',ascending=False)

              count           sum       mean
market
Europe        50252  1.169443e+06  23.271571
LATAM         51594  1.123322e+06  21.772330
Pacific Asia  41260  8.577534e+05  20.788983
USCA          25799  5.643138e+05  21.873475
Africa        11614  2.520712e+05  21.704080

In [81]:
df.head()

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,product_image,product_name,product_price,product_status,shipping_date_(dateorders),shipping_mode,order_year,order_month,order_month_name,shipping_days
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class,2018,1,January,3
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class,2018,1,January,5
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class,2018,1,January,4
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class,2018,1,January,3
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class,2018,1,January,2

In [82]:
pip install sqlalchemy pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: pyodbc in C:\ProgramData\anaconda3\Lib\site-packages (5.3.0)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [83]:
import pyodbc 
pyodbc . drivers()

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'ODBC Driver 18 for SQL Server']

In [94]:

import pyodbc

pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=localhost\\SQLEXPRESS;"
    "DATABASE=DataCo_supplychain;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

print("Connected Successfully!")

Connected Successfully!

In [95]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

params = quote_plus(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=localhost\\SQLEXPRESS;"
    "DATABASE=DataCo_supplychain;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

In [96]:
pd.read_sql(
    "SELECT DB_NAME() AS database_name",
    engine
)

        database_name
0  DataCo_supplychain

In [99]:
df.to_sql('supply_chain',
          con=engine,
          if_exists ='replace',
          index =False)

19

In [100]:
pd.read_sql('SELECT TOP 5 * from supply_chain',
            engine)

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,product_image,product_name,product_price,product_status,shipping_date_(dateorders),shipping_mode,order_year,order_month,order_month_name,shipping_days
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class,2018,1,January,3
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class,2018,1,January,5
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class,2018,1,January,4
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class,2018,1,January,3
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class,2018,1,January,2